---
title: "Bootstrap probability"
author: "Edgart Flores"
date: "12/17/2020"
output: html_document
---

# You probably don't need all of these packages 

```{r setup, include=FALSE}
library(dplyr)
library(readr)
library(tidyverse)
library(latex2exp)
library(readxl)
library(here) 
library(broom)
library(ggplot2)
library(RColorBrewer)
library(scales)
library(reshape2)
library(dendextend)
library(cowplot)
library(ggdendro)
library(graphics)
library(vegan)
library(pvclust)
library(cluster)
library(factoextra)
library(magrittr)
library(janitor)
library(ade4) 
library(adespatial) 
library(gclus) 
library(cluster) 
library(FD)
library(ggpubr)

library(scico)
library(pals)
library(viridis)
library(lmodel2)
library(ggpmisc)
library(wesanderson)
``` 


# date: final-corrected

# remove NA
```{r, message=FALSE}
final_corrected <- subset(final_corrected,  ! paste(id,sep="_") %in% c("NA") )
```

```{r cars}
final_corrected <- select(final_corrected, id_new, class, relab) 
final_corrected <- dcast(final_corrected, id_new ~ class, value.var = c("relab"))
final_corrected <- data.frame(final_corrected[,-1], row.names=final_corrected[,1])

final_corrected[is.na(final_corrected)] <- 0 # transform all NA into zeros
```


# special case = I need to transpose this data for a probability cluster.

```{r cars}
Approximately_Unbiased <- data.frame(t(final_corrected))
```

# calculating the probabilities!!!

#Approximately_Unbiased

```{r cars}
Approximately_Unbiased <- data.frame(t(final_corrected))
# Se generan solo 10000 pseudo-muestras para agilizar el proceso, pero para casos
# reales los autores no recomiendan bajar de 10000
boot_hc_cluster <- pvclust(data = Approximately_Unbiased, method.dist = "euclidea",
                           method.hclust = "average",
                           nboot = 10, quiet = T)
# Al representar un objeto pvclust se obtiene el dendrograma con los valores de
# AU-pvalue en rojo y BP-values en verde
plot(boot_hc_cluster, cex = 0.8, print.num = F, cex.pv = 0.8)

# Con la función pvrect() se encuadran aquellos clusters significativos para una
# confianza del 95%.
pvrect(x = boot_hc_cluster, alpha = 0.95, pv = "au")
```


